import 'package:editor_widgets/tabbed_layout.dart';
import 'package:flutter/material.dart';

/// TabbedDocument represent a document in [TabbedLayout] widget
class TabbedDocument {

  /// unique id provided by consumer
  String id;

  /// document name
  String name;

  /// optional document icon
  Widget? icon;

  /// autogenerated internal key to search document in widget tree
  GlobalKey _key = GlobalKey();

  /// function to construct widget
  Widget Function(BuildContext context)? widgetBuilder;

  /// default constructor
  TabbedDocument({required this.id, required this.name, this.icon, this.widgetBuilder});

  /// get key associated with document. (autogenerated)
  GlobalKey get key => _key;

  @override
  bool operator ==(Object other) {
    if (other is! TabbedDocument) {
      return false;
    }
    return id==other.id;
  }
}
